
language: node_js
node_js: 
 - "8"
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - npm run cover
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=Belthgorr_myCalculator -Dsonar.projectKey=belthgorr -Dsonar.sources='./app' -X
